abundance(a, s1, down). 
abundance(a, s2, down).
abundance(a, s3, down). 
abundance(a, s4, down).
abundance(b, s1, up). 
abundance(b, s2, up).
abundance(b, s3, down). 
abundance(b, s4, down).
abundance(c, s1, down).
abundance(c, s2, down).
abundance(c, s3, up). 
abundance(c, s4, up). 
abundance(d, s1, up).
abundance(d, s2, up).
abundance(d, s3, down).
abundance(d, s4, down).
abundance(e, s1, up).  
abundance(e, s2, up).
abundance(e, s3, down).  
abundance(e, s4, down). 
abundance(f, s1, down). 
abundance(f, s2, down). 
abundance(f, s3, up). 
abundance(f, s4, up).
